min-players: 2
border-radius-per-player: 25

terrain-search:
  optimal-y: 128
  locations-per-terrain: 3
  execution-timeout-millis: 5

  origin-search:
    outer-radius: 1000000
    inner-radius: 2048

  structure-search:
    radius: 1024
    delta: 256

  optimal-selection:
    attempts: 4
    min-offset: 16
    max-offset: 48
    radius: 128
    delta: 4
    threshold: 0.5

grind-stage:
  duration-seconds: 300

  enhancements:
    ore-generation-enhancement:
      enabled: true
      replacement-chance: 0.2
      replacements:
        coal-ore: [copper_ore, iron_ore]
        deepslate-coal-ore: [deepslate_copper_ore, deepslate_iron_ore]
        copper-ore: [iron_ore]
        deepslate-copper-ore: [deepslate_iron_ore]
        iron-ore: [gold_ore, lapis_ore]
        deepslate-iron-ore: [deepslate_gold_ore, deepslate_lapis_ore]
        gold-ore: [diamond_ore]
        deepslate-gold-ore: [deepslate_diamond_ore]
        lapis-ore: [diamond_ore]
        deepslate-lapis-ore: [deepslate_diamond_ore]
        redstone-ore: [diamond_ore]
        deepslate-redstone-ore: [deepslate_diamond_ore]
        emerald-ore: [diamond_ore]
        deepslate-emerald-ore: [deepslate_diamond_ore]

    ore-loot-increase:
      enabled: true
      min-modifier: 3
      max-modifier: 5

    mob-loot-increase:
      enabled: true
      min-modifier: 3
      max-modifier: 5

    smelting-acceleration:
      enabled: true
      speed-modifier: 0.25

    blast-furnace-upgrade:
      enabled: true

    smoker-upgrade:
      enabled: true

    crafting-table-enchantment:
      enabled: true
      levels:
        default: 15
        wooden: 5
        stone: 5
        copper: 5
        leather: 10
        chainmail: 15
        iron: 10
        golden: 20
        diamond: 25
        netherite: 30

    apple-chance-increase:
      enabled: true
      chance-modifier: 5

fight-stage:
  border-narrowing-duration-seconds: 150
