name: OutlastZone
version: '1.0'
main: com.plummy.outlastzone.OutlastZone
api-version: '1.21'
authors: [ Plummy ]

permissions:
  outlastzone.command:
    default: op

commands:
  outlastzone:
    description: Manage OutlastZone game
    usage: /outlastzone <start | stop | reload | help>
    permission: outlastzone.command
    aliases:
      - outlast
      - oz
